version: '3.8'

services:
  # Service untuk Backend FastAPI
  backend:
    image: dhimashadid/psiko-bot-backend:latest
    container_name: psikobot-backend
    restart: unless-stopped
    env_file:
      - .env # Menggunakan variabel dari file .env
    volumes:
      - ./common/data:/app/common/data # Mount volume untuk data RAG (ChromaDB, PDF)
    networks:
      - app-network
    expose:
      - "8000" # Port internal, tidak diekspos ke host

  # Service untuk Bot Telegram
  bot:
    image: dhimashadid/psiko-bot-bot:latest
    container_name: psikobot-telegram
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./common/data:/app/common/data # Mount volume yang sama untuk data RAG
    depends_on:
      - backend # Pastikan backend jalan dulu sebelum bot
    networks:
      - app-network

  # Service untuk Nginx Reverse Proxy
  nginx:
    image: nginx:1.25-alpine
    container_name: psikobot-nginx
    restart: unless-stopped
    ports:
      - "80:80" # Memetakan port 80 dari host ke port 80 di container
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge